#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias srv="python -m SimpleHTTPServer"
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
nvm alias default v0.12 2>&1 > /dev/null
nvm use default 2>&1 > /dev/null
eval `docker-machine env docker`
